### ISSUE TITLE
api response structure

### ISSUE THREAD

**Issue by kraccoon-dev** [Dot-Line-20/self-develop-server#4]
api 구조에대한 이슈입니다. 현재 api의 정해진 응답 규칙이 없어, [JSend](https://github.com/omniti-labs/jsend)를 확장하여 응답형식을 확립할 예정입니다.
구조 초안은 아래와 같으며, 자유롭게 의견 말씀해 주세요.
```ts
{
  status: 'success' | 'fail' | 'error' // status of server response
  message?: string // message for status 
  data?: unknown // sended data will be here
}
```

**Comment by H2Owater425** [comment]
통상적인 REST API 사양에 따르면 API는 요청의 처리 상태 또는 결과를 표현하기 위해 HTTP 상태 코드를 사용하지만, JSend 표준은 실질적인 개발자의 편의를 위해 이를 무시하고 응답 객체의 요소로서 다룬다고 명시되어 있습니다.
그런고로, REST API와 JSend 중 어느 사양을 따라야 하는지 알고 싶습니다.

**Comment by kraccoon-dev** [comment]
@H2Owater425
JSend은 REST 스타일 애플리케이션에서 메시징에 초점을 둔 포멧으로, 이미 Rest api를 사용한다는점을 전제가 되어 있는것 같습니다.

> Uniform interface. All API requests for the same resource should look the same, no matter where the request comes from. The REST API should ensure that the same piece of data, such as the name or email address of a user, belongs to only one uniform resource identifier (URI). Resources shouldn’t be too large but should contain every piece of information that the client might need.

그리고 응답을 보낼 떄 http status code는 언제나 함께 전달되기 때문에 어느 형식을 사용하더라도 상태코드는 받을 수 있습니다.

 [IBM rest api 설계 원리](https://www.ibm.com/cloud/learn/rest-apis)의 '균일한 인터페이스' 규칙에 따라 일정한 응답 형식을 정하는것이 우리의 목표입니다. 

> JSend focuses on application-level (as opposed to protocol- or transport-level) messaging which makes it ideal for use in [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer)-style applications and APIs.

**Comment by H2Owater425** [comment]
죄송합니다, 질문이 조금 불명확했던 것 같아 조금 더 자세한 설명과 함께 질문드리고 싶습니다.
제 의도는 REST API의 표준이 HTTP 상태 코드(ex: delete -> 204 No content, post -> 201 Created)를 통해 요청의 상태를 표현하지만, JSend는 이와 같은 방식을 사용하지 않는다는 점(ex: delete -> 200 OK, post -> 200 OK)에서, 둘중 어느 것을 따라야 하는지였습니다.

**Comment by kraccoon-dev** [comment]
@H2Owater425 
> JSend는 이와 같은 방식을 사용하지 않는다는 점

[whither-http](https://github.com/omniti-labs/jsend#whither-http)에서 언급한것과 같이 status code는 사용할것입니다. 

> Therefore it is advised that server-side developers use both: provide a JSend response body, and whatever HTTP header(s) are most appropriate to the corresponding body.

(example of some response)
```
HTTP/1.1 400 Bad Request
{
    "status" : "fail",
    "message": "something went wrong"
}
```

**Comment by H2Owater425** [comment]
아하 그렇군요, 알겠습니다
