### ISSUE TITLE
change response method as jsend

### ISSUE THREAD

**Issue by kraccoon-dev** [Dot-Line-20/self-develop-server#7]
jsend를 사용하기 위해 res.json 또는 res.send를 변경해 주세요. (`\sres.*\.(json|send)` 으로 검색)
https://www.npmjs.com/package/jsend

**Comment by H2Owater425** [comment]
향후로는 해당 페키지를 이용해 응답 객체를 송신하면 되는건가요?

**Comment by kraccoon-dev** [comment]
@H2Owater425 네
